--@block
CREATE VIEW EMPSALARY AS 
    SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY
        FROM employees;
--@block
SELECT * FROM EMPSALARY;
--@block
CREATE OR REPLACE VIEW EMPSALARY AS 
    SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE, MIN_SALARY, MAX_SALARY
    FROM EMPLOYEES, JOBS
    WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;
